name: Telegram VLESS

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install
        run: |
          pip install -r requirements.txt

      - name: Run Script
        env:
          TG_STRING_SESSION: ${{ secrets.TELEGRAM_STRING_SESSION }}
          MY_TG_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: |
          python main.py

      - name: Commit Output
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add vless_last_24h.txt

          git commit -m "update configs" || echo "No changes"

          git push
